const GET_LIST_USER_REQUEST = 'GET_LIST_USER_REQUEST';
const GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS';
const GET_LIST_USER_FAIL = 'GET_LIST_USER_FAIL';

const actionTypes = {
    GET_LIST_USER_FAIL,
    GET_LIST_USER_REQUEST,
    GET_LIST_USER_SUCCESS
}

export default actionTypes;